include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - lib/**/*.g.dart
    - lib/generated/**/*.dart

linter:
  rules:
    avoid_equals_and_hash_code_on_mutable_classes: false
    avoid_slow_async_io: false
    library_private_types_in_public_api: false
    lines_longer_than_80_chars: false
    no_adjacent_strings_in_list: false
    no_default_cases: false
    only_throw_errors: false
    prefer_asserts_with_message: false
    public_member_api_docs: false